MVC_Israel/MVC_Israel/Models/Autores.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_Israel.Models
{
    public class Autores
    {
        public byte IdAutor { get; set; }
        public string Nome { get; set; }
        public string Pais { get; set; }
    }
}

MVC_Israel/MVC_Israel/Controllers/AutoresController.cs
using MVC_Israel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Israel.Controllers
{
    public class AutoresController : Controller
    {
        livrariaEntities livraria = new livrariaEntities();

        // GET: Autor
        public ActionResult Index()
        {
            List<Autores> Listautores = new List<Autores>();
            var AutoresBanco = livraria.Autor.ToList();

            foreach(Autor item in AutoresBanco)
            {
                Autores autores = new Autores();
                autores.IdAutor = item.IdAutor;
                autores.Nome = item.Nome;
                autores.Pais = item.Pais;

                Listautores.Add(autores);
            }

            return View(Listautores);
        }
        public ActionResult Create()
        {
            return View();
        }



        [HttpPost]
        public ActionResult Create(Autores autores)
        {
          //  byte id_autor = byte.Parse((DateTime.Now.Millisecond/10));
            Autor autor = new Autor();
            autor.IdAutor = 10;
            autor.Nome = autores.Nome;
            autor.Pais = autores.Pais;
            livraria.Autor.Add(autor);
            livraria.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int IdAutor)
        {
            var Autor = livraria.Autor.Where(a => a.IdAutor == IdAutor).FirstOrDefault();//bd

            Autores autores = new Autores();//model
            autores.IdAutor = Autor.IdAutor;
            autores.Nome = Autor.Nome;
            autores.Pais = Autor.Pais;
            return View(autores);
        }

        [HttpPost]
        public ActionResult Edit(Autores autores)
        {
            var autor = livraria.Autor.Where(a => a.IdAutor == autores.IdAutor).FirstOrDefault();
            autor.Nome = autores.Nome;
            autor.Pais = autores.Pais;
            livraria.SaveChanges();

            return RedirectToAction("Index");
        }


        public ActionResult Delete(int IdAutor)
        {
            var Autor = livraria.Autor.Where(a => a.IdAutor == IdAutor).FirstOrDefault();//bd
            Autores autores = new Autores();//model
            autores.IdAutor = Autor.IdAutor;
            autores.Nome = Autor.Nome;
            autores.Pais = Autor.Pais;
            return View(autores);
        }

        [HttpPost]
        public ActionResult Delete(Autores autores)
        {
            var autor = livraria.Autor.Where(a => a.IdAutor == autores.IdAutor).FirstOrDefault();
            autor.Nome = autores.Nome;
            autor.Pais = autores.Pais;
            livraria.Autor.Remove(autor);
            livraria.SaveChanges();

            return RedirectToAction("Index");
        }


    }
}

MVC_Israel/MVC_Israel/Views/Autores/Create.cshtml
@using MVC_Israel.Models
@model Autor


@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid mt-">

    @using (Html.BeginForm("Create"))
    {
        <div class="form-group">
            <label for="exampleInputEmail1">Nome</label>
            <input type="text" class="form-control" name="Nome" id="Nome" aria-describedby="emailHelp">
        </div>

        <div class="form-group">
            <label for="exampleInputPassword1">Pais</label>
            <input type="text" class="form-control" name="Pais" id="Pais">
        </div>

        <button type="submit" class="btn btn-primary">Adicionar</button>
    }

</div>

MVC_Israel/MVC_Israel/Views/Autores/Delete.cshtml
@using MVC_Israel.Models
@model Autores
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid mt-">

    @using (Html.BeginForm("Delete"))
    {
        <div class="form-group">
            <label for="exampleInputEmail1">Nome</label>
            <input type="text" class="form-control" readonly name="IdAutor" hidden="hidden" id="IdAutor" value="@Model.IdAutor">
            <input type="text" class="form-control" readonly name="Nome" id="Nome" value="@Model.Nome" aria-describedby="emailHelp">
        </div>

        <div class="form-group">
            <label for="exampleInputPassword1">Pais</label>
            <input type="text" class="form-control" readonly name="Pais" id="Pais" value="@Model.Pais">
        </div>

        <button type="submit" class="btn btn-danger">Deletar</button>
    }

</div>

MVC_Israel/MVC_Israel/Views/Autores/Edit.cshtml
@using MVC_Israel.Models
@model Autores

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid mt-">

    @using (Html.BeginForm("Edit"))
    {
        <div class="form-group">
            <label for="exampleInputEmail1">Nome</label>
            <input type="text" class="form-control" name="IdAutor" hidden="hidden" id="IdAutor" value="@Model.IdAutor">
            <input type="text" class="form-control" name="Nome" id="Nome" value="@Model.Nome" aria-describedby="emailHelp">
        </div>

        <div class="form-group">
            <label for="exampleInputPassword1">Pais</label>
            <input type="text" class="form-control" name="Pais" id="Pais" value="@Model.Pais">
        </div>

        <button type="submit" class="btn btn-primary">Adicionar</button>
    }

</div>

MVC_Israel/MVC_Israel/Views/Autores/Index.cshtml
@using MVC_Israel.Models;
@model List<Autores>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />

<div class="container-fluid">
    <div class="row col-md-3">
        <h1 class="text-capitalize "> Autores</h1>
        @Html.ActionLink("Cadastrar", "Create", "Autores", new { @class = "btn btn-primary" })
    </div>
</div>


<div class="container"> 
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Nome</th>
                <th scope="col">Pais</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {

                <tr>
                    <th scope="row">@item.IdAutor</th>
                    <td>@item.Nome</td>
                    <td>@item.Pais</td>
                    <td>
                        @Html.ActionLink("Deletar", "Delete", "Autores", new { IdAutor = item.IdAutor }, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Editar", "Edit", "Autores", new { IdAutor = item.IdAutor }, new { @class = "btn btn-primary" })
                    </td>
                </tr>
            }
        </tbody>
        </table>
</div>