MVC_Israel/MVC_Israel/Models/Livro.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Israel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livro
    {
        public int IdLivro { get; set; }
        public string Nome { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public byte IdAutor { get; set; }
        public string IdEditora { get; set; }
        public string IdGenero { get; set; }
        public int QuantidadePaginas { get; set; }
        public int Classificacao { get; set; }
    
        public virtual Autor Autor { get; set; }
    }
}

MVC_Israel/MVC_Israel/Models/Livros.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_Israel.Models
{
    public class Livros
    {
        public int IdLivro { get; set; }
        public string Nome { get; set; }
        public DateTime DataCadastro { get; set; }
        public Autores Autores { get; set; }
        public string Editora { get; set; }
        public string Genero { get; set; }
        public int QuantidadePaginas{ get; set; }
        public int Classificacao { get; set; }


    }
}

MVC_Israel/MVC_Israel/Controllers/LivrosController.cs
using MVC_Israel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Israel.Controllers
{
    public class LivrosController : Controller
    {
        livrariaEntities livraria = new livrariaEntities();
        
        // GET: Livro
        public ActionResult Index()
        {
            List<Livros> livros = new List<Livros>();
            var LivrosBanco = livraria.Livro.ToList();


            System.Collections.IList list = LivrosBanco;
            for (int i = 0; i < list.Count; i++)
            {
                Livro item = (Livro)list[i];
                Livros liv = new Livros();
                liv.IdLivro = item.IdLivro;
                liv.Nome = item.Nome;
                liv.Editora = item.IdEditora;
                liv.Genero = item.IdGenero;
               // liv.Autores.Nome = item.Autor.Nome;
                liv.QuantidadePaginas = item.QuantidadePaginas;
                liv.DataCadastro = DateTime.Now;
                liv.Classificacao = item.Classificacao;
                livros.Add(liv);
            }



            return View(livros);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Livros livros)
        {
            Livro liv = new Livro();
            liv.IdLivro = livros.IdLivro;
            liv.Nome = livros.Nome;
            liv.IdEditora = livros.Editora;
            liv.IdGenero = livros.Genero ;
            liv.Classificacao = livros.Classificacao;
            liv.DataCadastro = livros.DataCadastro;
            
            livraria.Livro.Add(liv);
            livraria.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int idLivro)
        {
            var livro = livraria.Livro.Where(a => a.IdLivro == idLivro).FirstOrDefault();//bd
            Livros liv = new Livros();
            // Autores autores = new Autores();//model
            liv.IdLivro = livro.IdLivro;
            liv.Nome = livro.Nome;
            liv.Genero = livro.IdGenero;
            liv.Editora = livro.IdEditora;
            liv.DataCadastro = DateTime.Now;
            liv.QuantidadePaginas = livro.QuantidadePaginas;
            liv.Classificacao = livro.Classificacao;
            return View(liv);
        }

        [HttpPost]
        public ActionResult Edit(Livros livros)
        {
            var liv = livraria.Livro.Where(a => a.IdLivro == livros.IdLivro).FirstOrDefault();
            liv.IdLivro = livros.IdLivro;
            liv.Nome = livros.Nome;
            liv.DataCadastro = livros.DataCadastro;
            liv.IdEditora = livros.Editora;
            liv.IdGenero = livros.Genero;
            liv.Classificacao = livros.Classificacao;
            liv.IdAutor = 1;
            liv.QuantidadePaginas = livros.QuantidadePaginas;
            livraria.SaveChanges();

            return RedirectToAction("Index");
        }


        public ActionResult Delete()
        {
            return View();
        }

    }
}

MVC_Israel/MVC_Israel/Views/Livros/Create.cshtml
@using MVC_Israel.Models
@model Livros

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container-fluid mt-">

    @using (Html.BeginForm("Create"))
    {
        <div class="form-group">
            <label for="exampleInputEmail1">Nome</label>
            <input type="text" class="form-control" name="Nome" id="Nome" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Genero</label>
            <input type="text" class="form-control" name="Genero" id="Genero" aria-describedby="emailHelp">
        </div>

        <div class="form-group">
            <label for="exampleInputEmail1">Data de Cadastro</label>
            <input type="date" class="form-control" name="DataCadastro" id="DataCadastro" aria-describedby="emailHelp">
        </div>

        <div class="form-group">
            <label for="exampleInputEmail1">Classificão</label>
            <input type="number" class="form-control" name="Classificacao" id="Classificacao" aria-describedby="emailHelp">
        </div>

        <div class="form-group">
            <label for="exampleInputEmail1">Editora</label>
            <input type="text" class="form-control" name="Editora" id="Editora" aria-describedby="emailHelp">
        </div>

        //Editora

        <button type="submit" class="btn btn-primary">Adicionar</button>
    }

</div>

MVC_Israel/MVC_Israel/Views/Livros/Delete.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>delete</h1>

MVC_Israel/MVC_Israel/Views/Livros/Edit.cshtml
@using MVC_Israel.Models
@model Livros

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<div class="container-fluid mt-">

    @using (Html.BeginForm("Edit"))
    {
        <div class="form-group">
            <label for="exampleInputEmail1">Nome</label>
            <input type="text"  name="IdLivro" hidden  id="IdLivro" value="@Model.IdLivro">
            <input type="text" class="form-control" name="Nome" id="Nome" value="@Model.Nome" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Data de Cadastro</label>
            <input type="date" class="form-control" name="DataCadastro" id="DataCadastro" value="@Model.DataCadastro">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Genero</label>
            <input type="text" class="form-control" name="Genero" id="Genero" value="@Model.Genero">
        </div>
        @*<div class="form-group">
            <label for="exampleInputEmail1">Genero</label>
            <input type="text" class="form-control" name="Nome" id="Nome" value="@Model.Autores.Nome">
        </div>*@
        <div class="form-group">
            <label for="exampleInputEmail1">Editora</label>
            <input type="text" class="form-control" name="Editora" id="Editora" value="@Model.Editora">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Quantidade de paginas</label>
            <input type="text" class="form-control" name="QuantidadePaginas" id="QuantidadePaginas" value="@Model.QuantidadePaginas">
        </div>

        <button type="submit" class="btn btn-primary">Adicionar</button>
    }

</div>

MVC_Israel/MVC_Israel/Views/Livros/Index.cshtml
@using MVC_Israel.Models;
@model List<Livros>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <div class="row col-md-3">
        <h1 class="text-capitalize "> Livros</h1>
        @Html.ActionLink("Cadastrar", "Create", "Livros", new { @class = "btn btn-primary" })
    </div>
</div>

<div class="container">
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Nome</th>
                <th scope="col">Data de Cadastro</th>
                <th scope="col">Autor</th>
                <th scope="col">Editora</th>
                <th scope="col">Genero</th>
                <th scope="col">Quantidade de paginas</th>
                <th scope="col">Classificação</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {

            <tr>
                <th scope="row">@item.IdLivro</th>
                <td>@item.Nome</td>
                <td>@item.DataCadastro</td>
                <td>@*//@item.Autores.Nome*@</td>
                <td>@item.Editora</td>
                <td>@item.Genero</td>
                <td>@item.QuantidadePaginas</td>
                <td>@item.Classificacao</td>
                <td>
                    @Html.ActionLink("Deletar", "Delete", "Livros", new { IdLivro = item.IdLivro }, new { @class = "btn btn-primary" })
                    @Html.ActionLink("Editar", "Edit", "Livros", new { IdLivro = item.IdLivro }, new { @class = "btn btn-primary" })
                </td>
            </tr>
            }

        </tbody>
            </table>